# Generated by Django 3.1.2 on 2020-12-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome da Pessoa')),
                ('profissao', models.CharField(choices=[('ENGENHEIRO', 'Engenheiro'), ('PROFESSOR', 'Professor'), ('ESTUDANTE', 'Estudante')], max_length=150, null=True, verbose_name='Profissão')),
                ('endereco', models.CharField(blank=True, max_length=150, null=True, verbose_name='Endereço')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Numero')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('login', models.CharField(max_length=50, unique=True, verbose_name='Login')),
                ('password', models.CharField(max_length=128, verbose_name='Senha')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True, verbose_name='Último login')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=True, verbose_name='Staff')),
                ('groups', models.ManyToManyField(blank=True, to='auth.Group')),
                ('user_permissions', models.ManyToManyField(blank=True, to='auth.Permission')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
